[lint]
select = [
    # pycodestyle
    "E",
    "W",
    # Pyflakes
    "F",
    "ANN",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # Pylint
    "PLR"
]
ignore = [
    "PLR2004"
]
