name: Collect progress percentage

on:
    schedule:
        - cron: '0 */2 * * *'
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            
            - name: setup python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'
            
            - name: install packages
              run: |
                python -m pip install --upgrade pip
                pip install requests
            
            - name: execute script
              env:
                STEPIK_CLIENT_ID: ${{ secrets.STEPIK_CLIENT_ID }}
                STEPIK_CLIENT_SECRET: ${{ secrets.STEPIK_CLIENT_SECRET }}
              run: python get_progress.py
